### ISSUE TITLE
Text-only version

### ISSUE THREAD

**Issue by bluerook17** [haslo/lists_juggle_browser#60]
It'd be nice to copy-paste the output into a spreadsheet, but the pictures don't play nice with them. Can we get a text-only option which removes the card image and uses text for the factions?

**Comment by haslo** [comment]
I think an actual CSV or Excel download would be more useful than a text version though, right? Wouldn't really give more to do, and it would probably be less prone to copy-paste errors (though Excel sucks at importing CSV without making mistakes...)

**Comment by bluerook17** [comment]
Yup, a download option would probably be a better idea.

**Comment by haslo** [comment]
ETA 10 hours, methinks 😁 I'm doing an UTF8 CSV export.

And I'll do #41 as well while I'm at it.

**Comment by haslo** [comment]
@bluerook17 There's a CSV export link in a couple of places now. If you import it in Excel, you'll have to make sure to tell Excel that you're actually using the CSV standard they way it was intended and not Excel's interpretation of it:

* UTF-8 encoding
* Comma-separated (not tabs or anything)
* Escaped with `"`
