### ISSUE TITLE
Allow Archetype Name Submission

### ISSUE THREAD

**Issue by ikejames** [haslo/lists_juggle_browser#64]
This isn't a huge need. I understand that. That doesn't change the fact I want to name the Archetype I fly before some other, clearly less talented, player names it.

**Comment by haslo** [comment]
Thanks for the suggestion! Of course, your talent deserves recognition!

It used to be possible to just name any archetypes at any time, and then suddenly all the names said KRAYT for some reason (thus this commit: 036a5d77f504e39d0a16193392fe203493e40a2a). I'm working on something to replace that 😄

**Comment by ikejames** [comment]
Gah! Someone named it already! TARK?! FUCKING TARK!?!?!?? 

Stupid name.

GET WRECKED!!!!!!

:)
