### ISSUE TITLE
X Wing ACT Regionals @ Jolt seems to have been uploaded dozens of times 

### ISSUE THREAD

**Issue by zavrtak** [haslo/lists_juggle_browser#89]
http://meta-wing.com/ship_combos/5222/squadrons?ranking_start=2018-01-26&

**Comment by haslo** [comment]
Gee, interesting! Thanks, I'll look into it. It's possible that it was uploaded and deleted to Lists Juggler multiple times, I don't think I delete anything if it was imported at least once before...

**Comment by haslo** [comment]
Looks like the duplicates are cleaned up on the Lists Juggler end, I'll be able to fix it on my end in a couple hours 👍

**Comment by haslo** [comment]
...and fixed 😄 Thanks for the report!
