### ISSUE TITLE
Suggestion: Add FAQ Effective Dates As Pre-Populated Start Dates

### ISSUE THREAD

**Issue by oSPANNERo** [haslo/lists_juggle_browser#93]
Just a small suggestion to add the FAQ Effective Dates to the pre-populated filter drop down. (Maybe just putting in 4.4.1 and adding the new ones going forward?)

They tend to have decent impact on the meta so are relevant analytical inflection points.

EG:
4.4.1 (01.22.2018) = Harpooned / Trajectory Simulator
4.2.2 (10.24.2016) = Attanni Mindlink / Biggs Darklighter

**Comment by haslo** [comment]
The Biggs / Attanni was effective from 2017-11-06 (announced 2017-10-24) and is in the list, but I should probably add Attanni to its description. I can add Harpooned / Trajectory Simulator, too. Will do later today.

Thanks for the suggestion!

**Comment by oSPANNERo** [comment]
Thanks for even considering the request! Fairly new around here and had a few experiences with FAQ'd cards so I tend to filter the data to "latest relevant".

And sorry for any confusion on Biggs/Attanni. I was basing my effective date for 4.2.2 / 4.2.3 off the bottom of the first page of the FAQs where they both say "EFFECTIVE 10.24.2016" and the FFG news article on 10.17.16 describing the release of 4.2.2

However, being new, Its likely I am just misreading/misunderstanding or am missing some relevant nuance so I'll happily defer to your expertise.

---------------------------------------

https://www.fantasyflightgames.com/en/news/2016/10/17/a-test-of-your-skills/

https://images-cdn.fantasyflightgames.com/filer_public/a5/6e/a56ef1c3-6fe3-46e8-9a7b-4bb840c9a6e3/x-wing_faq_v422_high_res.pdf

https://images-cdn.fantasyflightgames.com/filer_public/95/aa/95aa1708-4b04-4aca-8397-02d9d4247bcb/x-wing_faq_v423.pdf

**Comment by haslo** [comment]
Yeah, the date in that one was a copy paste error on FFG's part. Here's the news article announcing the Biggs FAQ:

https://www.fantasyflightgames.com/en/news/2017/10/25/new-squadron-formations/

You had me worried that I had the date wrong though 😁

**Comment by haslo** [comment]
![screen shot 2018-06-06 at 10 33 35](https://user-images.githubusercontent.com/102580/41026539-19aa4aec-6975-11e8-97dd-95b795a1f787.png)

Thanks again 👍
