### ISSUE TITLE
Addition of Wave 14 Components

### ISSUE THREAD

**Issue by oSPANNERo** [haslo/lists_juggle_browser#94]
I may just be ahead of the curve a little but could you please add the contents of Wave 14 expansions? I looked at Juggler and quick search shows results for the Reaper ship and Scarif Base Pilot but not much for Saw's Renegades.

**Comment by stickus** [comment]
Seconding this! I would love to use the Squadron Visualizer to print my lists, but it doesn't seem to support the Wave 14 ships yet.

**Comment by haslo** [comment]
Thanks for the heads-up, @oSPANNERo and @stickus! Done!
