### ISSUE TITLE
Tie Reaper Missing Icon

### ISSUE THREAD

**Issue by oSPANNERo** [haslo/lists_juggle_browser#96]
This may be a function of it not existing but its odd-man-out at this point.

**Comment by haslo** [comment]
Thanks! Looks like it's still missing from the font, too:

https://github.com/geordanr/xwing-miniatures-font/issues/48

I'll watch that issue and update meta-wing as soon as possible.

**Comment by haslo** [comment]
![screen shot 2018-07-20 at 09 26 54](https://user-images.githubusercontent.com/102580/42989084-13016c64-8bff-11e8-99c3-ae741275c8d8.png)

Fixed 😄
